### ISSUE TITLE
Add note about Heroku deployment

### ISSUE THREAD

**Issue by fjsj** [orcasgit/django-fernet-fields#2]
Deploying an app that depends on django-fernet-fields on Heroku does not work out-of-the-box if only django-fernet-fields is specified on the requirements.txt (i.e. not its dependencies)

Heroku needs to know the app explicitly depends on `cffi` to install `libffi`. See:
https://github.com/heroku/heroku-buildpack-python/blob/5446d448fd3c06c369ff51c60344180796e7bf5d/bin/steps/cryptography#L23

Maybe it would be good to have a note about this on README?

**Comment by carljm** [comment]
In general it is a good idea to specify all requirements (even dependencies of dependencies) explicitly, for version pinning purposes.

I wouldn't mind a note in the docs about this.
